### ISSUE TITLE
Error: Create shell connection failed. Mongo binary might be corrupted.

### ISSUE THREAD

**Issue by IceApriler** [SouthbankSoftware/dbkoda#22]
system: osx
version: v1.0.0

i had set mongo binary path.
![image](https://user-images.githubusercontent.com/29689307/42073362-cb4727f4-7b98-11e8-8f69-52b4b2231594.png)
however it still error. why?
![image](https://user-images.githubusercontent.com/29689307/42073351-b9ee2b2e-7b98-11e8-9e99-8f8e0120da7c.png)
mongo is no problem  from the command.
![image](https://user-images.githubusercontent.com/29689307/42073427-425601f8-7b99-11e8-8fad-a5fe226af0c4.png)

i need you help, thanks very much.

**Comment by progress-mei** [comment]
我也碰到这种情况，同寻求解答

**Comment by progress-mei** [comment]
![image](https://user-images.githubusercontent.com/16767949/42080772-4c101d60-7bb6-11e8-9a52-c1cefb1c6e7d.png)

**Comment by guiguan** [comment]
@april-1993 @progress-mei 你们的`cat ~/.dbKoda/config.yml`是什么？

配置好`mongoCmd`以后，我的`config.yml`是这个样子的，连接正常
<img width="655" alt="screen shot 2018-07-04 at 6 16 30 pm" src="https://user-images.githubusercontent.com/940189/42265360-b03a825e-7fb6-11e8-9793-2b318bc9643a.png">

**Comment by IceApriler** [comment]
@guiguan 不好意思😅，貌似没注意到关于这个issue的邮件，我 cat ~/.dbKoda/config.yml后是下面这样的。
```
user:
  id: TX_cbAAQ9naTlfF7vRKQX
mongoCmd: /usr/local/mongodb/bin/mongo
drillCmd: null
drillControllerCmd: null
mongoVersionCmd: null
mongoexportCmd: null
mongoimportCmd: null
mongodumpCmd: null
mongorestoreCmd: null
telemetryEnabled: true
showNewFeaturesDialogOnStart: true
tableOutputDefault: true
automaticAutoComplete: true
showWelcomePageAtStart: true
passwordStoreEnabled: false
dockerEnabled: false
docker:
  createNew: true
  imageName: ''
  containerID: ''
  hostPath: ''
  containerPath: ''
  mongoCmd: docker run -it --rm  mongo
  mongorestoreCmd: docker run --rm  mongorestore
  mongodumpCmd: docker run --rm  mongodump
  mongoexportCmd: docker run --rm  mongoexport
  mongoimportCmd: docker run --rm  mongoimport
  mongoVersionCmd: docker run  mongo --version
performancePanel:
  preventDisplaySleep: false
  metricSmoothingWindow: 6
  foregroundSamplingRate: 5000
  backgroundSamplingRate: 15000
  historySize: 720
  historyBrushSize: 30
  alarmDisplayingWindow: 60000
maxOutputHistory: 1000
```
